### ISSUE TITLE
memory access out of bounds, Decoding failed

### ISSUE THREAD

**Issue by mohAmineBrs** [pmndrs/gltfjsx#132]
Hello there, 
I'm facing this error as showen in image while rendering this [floating-shoe](https://github.com/drcmda/floating-shoe) example and i don't know the real source of bug, any solution or even a hint.
The model was working 100% then i was working on an other component ib the same app without touching the model code then suddenly the error occured...I tried to reinstall the project file from this repos without any other componenet just the shoe model boilerplate, and the same error occured.
![floating-shoe](https://user-images.githubusercontent.com/74992534/154655435-72275aa8-6a8d-433d-8374-d1433300a38b.PNG)

**Comment by donmccurdy** [comment]
Likely cause is a recent update to the Draco CDN: 

- https://github.com/google/draco/issues/819

Updating to latest `@react-three/drei` should solve the issue, since it pins its Draco decoders to 1.4 instead of using the latest copy from the CDN.

**Comment by mohAmineBrs** [comment]
The update of `@react-three/drei` still throw the same error for me

**Comment by mohAmineBrs** [comment]
Hi, sorry for late reply because i was trying to find a way to a solution... but there is an improvment.
I changed the importing way of the `@react-three/fiber` and `@react-three/drei` components from this :
```
import { Canvas, useFrame } from "react-three-fiber"
import { ContactShadows, Environment, useGLTF, OrbitControls } from "drei"
```
to this :
```
import { Canvas, useFrame } from "@react-three/fiber"
import { ContactShadows, Environment, useGLTF, OrbitControls } from "@react-three/drei"
```
and it displayed this :
![Capture](https://user-images.githubusercontent.com/74992534/154795800-64181594-18cf-472a-afc4-5fc21e8d011e.PNG)

and throwed this error : 
![error](https://user-images.githubusercontent.com/74992534/154795817-a4c01ddb-6306-45a2-b0ad-a6c269f788a4.PNG)


Notice that the original model should look like this : 
![Capture1](https://user-images.githubusercontent.com/74992534/154795925-4b1e43b7-025e-43cf-b0dc-1ed9028cb5a9.PNG)

**Comment by donmccurdy** [comment]
Looks like the upstream issue with the Draco CDN has resolved: https://github.com/google/draco/issues/819#issuecomment-1046081914, you should be able to use the previous version of drei now.

The error you see above is caused by having versions of drei, three-stdlib, and/or three.js that do not match.

**Comment by mohAmineBrs** [comment]
Yesss, now it's working perfectly.
Thank you so much Mr @donmccurdy
